### ISSUE TITLE
Linear constraint parsing without advanced rules

### ISSUE THREAD

**Issue by bashtage** [matthewwardrop/formulaic#211]
It is possible to use a simpler parser when parsing linear constraints?  I am having problems with existing code that has variable names that were produced from formulaic, e.g., 

```python
import numpy as np
from formulaic.utils.constraints import LinearConstraints

cons = "ylocus_of_control_prog[T.general]"

variable_names = [
    "ylocus_of_control_Intercept",
    "ylocus_of_control_read",
    "ylocus_of_control_write",
    "ylocus_of_control_science",
    "ylocus_of_control_prog[T.general]",
    "ylocus_of_control_prog[T.vocational]",
    "yself_concept_Intercept",
    "yself_concept_read",
    "yself_concept_write",
    "yself_concept_science",
    "yself_concept_prog[T.general]",
    "yself_concept_prog[T.vocational]",
    "ymotivation_Intercept",
    "ymotivation_read",
    "ymotivation_write",
    "ymotivation_science",
    "ymotivation_prog[T.general]",
    "ymotivation_prog[T.vocational]",
]

lc = LinearConstraints.from_spec(cons, variable_names=variable_names)

```

The raises due to the presence of the ```[T.general]``` from the categorical expansion.

**Comment by matthewwardrop** [comment]
Hi @bashtage !

Thanks for bring this up again here to make sure I don't lose sight of it. IIUC, the request here is to remove the requirement for having to quote variables names in the linear constraint formula (as discussed elsewhere quoting the name of the column with backticks would work fine).

I took a quick look at this, and it actually looks like this is caused by an overzealous check in the tokenizer, the original motivation for which I have forgotten. Patching this resulted in the above code working as written. I'll push up this patch tomorrow :).

Thanks again for continuing to push on things on the statsmodels side!

**Comment by bashtage** [comment]
Thanks for this.  It is one of about 3 major stumbling blocks left.  The otherS are trying to match patsy ordering, which triggered the other PR, and some missing value handling, which needs some more investigation.
