### ISSUE TITLE
Index is not preserved in DataFrames after transformation

### ISSUE THREAD

**Issue by CamDavidsonPilon** [matthewwardrop/formulaic#23]
```python
df = pd.DataFrame([
    {'a': 1, 'b': 4},
    {'a': 2, 'b': 5},
    {'a': 3, 'b': 6},
])

df = df.set_index("b")
print(df.index)

from formulaic import Formula

df_ = formulaic.Formula('a').get_model_matrix(df)
print(df_.index)

```

This may be intentional (but I would argue it makes things more surprising and adds additional necessary code). Thoughts @matthewwardrop?

**Comment by matthewwardrop** [comment]
Hi @CamDavidsonPilon! Thanks for continuing to explore Formulaic :).

I vaguely recall that dropping the index was useful when we do filtering out of null values, but the dataframe index does seem like a useful thing to keep intact in some circumstances. I'll take a closer look soon! I probably haven't noticed this in my own work much because I always cast directly to numpy values (and now formulaic can do it for me using `output='numpy'`).

**Comment by matthewwardrop** [comment]
Hi @CamDavidsonPilon ; at long last I added support for keeping track of indices, even when dropping null columns. You can see [here](https://github.com/matthewwardrop/formulaic/commit/1f510b470881e2a48e953e76e95fc511a965c167) for the implementation details. This will be in v0.2.1 which I will release imminently.
