### ISSUE TITLE
Add helper methods for capturing contexts when using formulaic in libraries

### ISSUE THREAD

**Issue by CamDavidsonPilon** [matthewwardrop/formulaic#48]
Hi @matthewwardrop, looking for some advice here. I'm trying to debug [this issue](https://github.com/CamDavidsonPilon/lifelines/discussions/1337) occurring in lifelines. Internally, I'm using the `Formula` api, ex: something like `Formula(formula).get_model_matrix(data)`. I've narrowed the problem down to us _not_ using the context kwarg. I don't know what context to provide here. In the library, we having something like (I'm simplifying):

```
### users shell / script
def custom_func(x):
    return x + 1

CoxPHFitter().fit(...,df=df, formula="np.log10(x) + custom_func(x)")


### lifelines.estimation.coxph_fitter.py
...
def fit(self, df=None, formula=None ):
      return self.g(df, formula)

def g(self, df, formula)
    return self.regressors.transform_df(df, formula)
...


### lifelines.utils.__init__.py
...
    def transform_df(self, df, formula):
        return Formula(formula).get_model_matrix(df)
...
```

And so `get_model_matrix` never sees the context that contains `np` nor `custom_func`. 

In [`sugar.py`](https://github.com/matthewwardrop/formulaic/blob/main/formulaic/sugar.py), I've seen you retrieve the frame explicitly with `context=0`, but doesn't that only work if it is called from the top of the stack? What if we don't know where we are in the stack? 

A possibility is to do something like:

```
### lifelines.utils.__init__.py
...
    def transform_df(self, df, formula):
        import sys
        call_frame = sys._getframe(3)
        context = LayeredMapping(call_frame.f_locals, call_frame.f_globals)
        return Formula(formula).get_model_matrix(df, context=context))
...
```

But that relies on me knowing apriori that I need `3` there - which is too fragile and doesn't allow for any reuse. 

Have you seen other libraries get around this? What do you advise?

**Comment by matthewwardrop** [comment]
Hi @CamDavidsonPilon!

That's a great question. I'm also curious how things worked for you in the past (this should also have been a problem with patsy, no?).

In Formulaic, we have it easy, since `model_matrix` is syntactic sugar, is never used internally, and so can always just capture the calling environment, and it will do what people intuitively expect. For obvious reasons it's better not to use `model_matrix` in a library, so your approach is the recommended one (directly call `Formula().get_model_matrix()`).

As for how to get the right context in `lifelines`... that's a little trickier; especially if your classes are themselves nested in other libraries. If we can make the assumption that the right environment to capture is the one in which the constructor of your model class is called (e.g. `CoxPHFitter()`), then you should probably add some code that captures the environment there, and passes it down to formulaic. I'm happy to add some utility code in Formulaic to make the at bit easier (and to help others facing the same problem). Something like:

```
class CoxPHFitter:

    def __init__(self, ..., formula_context=None):
        if formula_context is None:
            formula_context = capture_caller_context(offset=...)
        # maybe add this as an instance attribute?
....
```

There are other *much* hackier solutions, including:
- Always parse the stack to find the first stack outside of lifelines or beyond some tagged frame (perhaps with a variable "__LIFELINE_TAG__") [this would likely work... but it is quite magic]
-  Same as above but *looking* for a specific tag. This requires users to add a variable or marker to their frame. [ick]
- Always using the ipython namespace if it exists: `get_ipython().user_ns` (assumes people use IPython/Jupyter) [ick]

Otherwise, I'm unaware of a generic solution to this; and it does seem cleaner to pass things down explicit rather than magically.

**Comment by matthewwardrop** [comment]
We could also allow `Formula` to capture an environment, and then update incoming strings to`Formula` instances in the constructor above. My only reservation is that we'd then be mixing config and state (which we'd need to drop during serialisation).

**Comment by johndburger** [comment]
> I'm also curious how things worked for you in the past (this should also have been a problem with patsy, no?).

FWIW, I had `import numpy as np` in the script where I was calling `CoxPHFitter.fit(formula="... + np.log10(x) ...")` and it magically worked with patsy. Maybe patsy walked up the stack looking for the right context?

**Comment by matthewwardrop** [comment]
Hmm.... that's really odd. I don't see any logic for that in Patsy. Moreover, this code demonstrates that it has the same behaviour as formulaic in this respect:

```
import patsy
from collections import defaultdict

def get_matrix(formula, data):
    return patsy.dmatrix(formula, data)

def wrapped():
    import numpy as np
    return get_matrix('np.log(x)', {'x': [1,2,3]})

wrapped()
```

Here we see that patsy's evaluation context does not include `np`, because it is just inheriting from its local/global context (rather than that of the caller).

**Comment by matthewwardrop** [comment]
Numpy is now available always as `np` (along with a few other helpful transforms like `log` and `exp`); see #e8173f914752e0f9002874c4c1773c8487d1ed07 for more details (or the grammar docs).

And once PR #63 merges, you'll have the helper function you were looking for @CamDavidsonPilon . Apologies for the lead time on this.
