### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by rluedde** [matthewwardrop/formulaic#5]
Hello Matt! The README says that Formulaic is a work in progress, is there anything that you'd like to see changed/added to the code that I might be able to help with? Writing tests? Docs? I don't have a strong programming/statistics/math background (yet) so I may not be much use with some things.

**Comment by matthewwardrop** [comment]
Hi Reilley! Thanks for reaching out!

Documentation is underway, but when it lands having someone read over it to make sure it makes sense and is correct would be hugely valuable. Likewise, if you start playing with the API and notice any friction points, now is the time to surface them (because we don't have to worry about API stability yet). Bug reporting is also helpful, but I'm less worried about bugs at this point than I am about getting the API right (we can always fix bugs, but changing the API frequently hurts users).

As for unit tests, we're at 100% coverage, but if you find something that breaks in user testing that is not represented by a test, feel free to open an issue or a PR, and we'll see if we cannot plug the hole!

**Comment by rluedde** [comment]
I'd love to read over the docs when the time comes!

Why is it that you don't have to start worrying about API stability yet? Does it have to do with releases? I'll start playing around with it this evening/tomorrow morning.

An API friction point, for example, could be confusing function names, confusing structure, or things along those lines, yeah?

I noticed that your first commit was very large, is that because those files were simply taken from elsewhere?

**Comment by matthewwardrop** [comment]
Hi again! Sorry for the lead time here.

We don't have to worry too much at this early stage about API stability because no one is using it. Later, once we start attracting users, it is much harder to change the API without breaking things for people.

And yes... friction points are exactly along those lines.

I wrote the contents of the initial commit over the course of two weeks, IIRC. During that time I didn't use version control (.... ahem!).

**Comment by rluedde** [comment]
Not a problem!

Gotcha. So now is the time for big changes if they are needed. I am going to spend a couple of hours right now playing around and will report back with questions/comments!

Why no VC early on?

**Comment by matthewwardrop** [comment]
> Not a problem!
> 
> Gotcha. So now is the time for big changes if they are needed. I am going to spend a couple of hours right now learning and will report back with questions/comments!
> 
> I'm not trying to be snarky, but how do you know that you will attract people? Is it because this sort of software is in demand?
I don't! I wrote it for myself and my needs, due to limitations in existing implementations. Time will tell whether people care about the improvements to the status quo here.
> 
> Why no VC early on?
This is a personal/hobby project that is motivated by real world use cases at my workplace and (presumably others). I work on it in my spare time, but I'm not planning to make a living off of this.
> 
> What does "high-level" vs "low-level" mean? Does a high level function have more more stuff abstracted away and therefore less stuff for the user to worry about?
"high-level" is more abstracted APIs (further/higher away from implementation details). "low-level" is the opposite: it's the nitty-gritty of how things are implemented.

**Comment by rluedde** [comment]
Thank you for the clarification, Matt!
