### ISSUE TITLE
BUG: SyntaxError converted to KeyError

### ISSUE THREAD

**Issue by bashtage** [matthewwardrop/formulaic#9]
I'm not sure if this should be considered syntax error, but if I try the formula

```
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.standard_normal((100,3)),columns=["y","y2","x"])
from formulaic import model_matrix
dep = model_matrix("y y2 ~ 1 + x", df, ensure_full_rank=False)
```

I get `KeyError: 'yy2'` which suggests the white space ie being trimmed.  FWIW patsy's tokenizer would raise SyntaxError on this.

**Comment by matthewwardrop** [comment]
Providing sensible errors and warning during the parsing process is still on the todo list (soon!). I think there is definitely room to improve here, since `y y2` is definitely a different error than `yy2` not existing in the data frame. I will update the tokeniser to raise a sensible exception here.

**Comment by matthewwardrop** [comment]
![image](https://user-images.githubusercontent.com/124910/87900069-10e1bd00-ca08-11ea-82bc-5d8e4a528b51.png)

**Comment by bashtage** [comment]
Thanks.
